### PR TITLE
added extra validation for nat64 prefix

### PR DESCRIPTION
**Pull request by reflog**
Attempt to fix https://github.com/getlantern/lantern-internal/issues/5091

@oxtoacart - thoughts? I know we in general try to avoid doing something 'predictable' like connecting to some known host, but I couldn't think of another approach.
Any suggestions are welcomed :)

WARNING - This template is public, do not include any sensitive information

- [ ] Do the tests pass? Consistently?
- [ ] Did this change improve test coverage?
- [ ] Has it been reviewed/approved by relevant teammates?
- [ ] Can it be QA’d in staging or something like staging?
- [ ] Is the code in question being linted? If not, consider adding a linter step to CI. If yes, make sure the linter is happy.
- [ ] Do we know how we’re going to deploy this?
- [ ] Are we clear on what the support and maintenance impact is?
- [ ] Did you create new documentation? Is it accessible and in the right place?
- [ ] Has existing documentation been updated?
- [ ] Have you logged tickets for related technical debt with the label “techdebt”?

### CODE REVIEW

**Comment by oxtoacart** [comment]
As long as Cloudflare's DNS server is widely used and not blocked this seems okay.

An alternate approach would be to bring back a modified version of your original fallback logic. If we have a prefix, try to dial via IPv6, but if that doesn't work, fall back to IPv4. If IPv4 works, stick to that until the prefix changes. It's a little more complex, but it has the advantage of not hitting a predictable server nor relying on that server to always be responsive.

**Comment by reflog** [comment]
@oxtoacart regarding my previous solution https://github.com/getlantern/netx/pull/15/files#diff-33ade2e9265ac10b48725ad84d3f41b93de3956b7f1b672fb99b87c21b369ed0L106-L111
if I remember correctly, you removed it since the way we detected 'unreachable' error was not bulletproof?

**Comment by oxtoacart** [comment]
@reflog 

> if I remember correctly, you removed it since the way we detected 'unreachable' error was not bulletproof?

Yes. What I suggested here would be slightly different. We would ignore the content/type of the error and always attempt to dial with IPv4.

**Comment by reflog** [comment]
@oxtoacart got it. thanks!

**Comment by oxtoacart** [comment]
> @oxtoacart got it. thanks!

To be clear, I'm not convinced my suggestion is better than what you have, it's just an idea. In curious what you think.

**Comment by reflog** [comment]
@oxtoacart well, your suggestion will require us to do the 'dial' twice. that's the only downside I see.
my suggestion would require additional dial per prefix change. not as bad, but more 'detectable'.  So I think I'll go with your suggestion

**Comment by reflog** [comment]
@oxtoacart thoughts?

**Review by oxtoacart — APPROVED** [review]

**Comment by reflog** [comment]
@oxtoacart - what packages that depend on netx would you suggest I bump to the new version?
I think at least flashlight, fronted, lantern-desktop, android-lantern and tlsdialer. anything I'm missing?

**Comment by oxtoacart** [comment]
@reflog There's a complete looking list from @hwh33 [here](https://github.com/getlantern/netx/pull/17#issuecomment-982788753). Since the public API hasn't changed, I think the minimum place where it's required is just flashlight. As long as lantern-desktop and android-lantern pull in the latest flashlight, they should in theory be okay then.

**Pull request merged**
